### ISSUE TITLE
Rename database to connection?

### ISSUE THREAD

**Issue by albireox** [sdss/sdssdb#10]
I think it makes a bit more sense to rename `database` to `connection`. For example

```
from sdssdb.peewee.sdss5db import catalogdb
catalogdb.connection.set_profile('sdssadmin')
```

We can keep both `connection` and `database` pointing to the same object, maybe with a deprecation warning for `database`?

**Comment by havok2063** [comment]
I'm not opposed to this on any fundamental level.  Does it make sense to separate out the idea of a database and a connection, and keep both around to reference different things?  It may not.  Just ruminating.  Is `dbconnection` too much?  

Just thinking out loud here...  Fundamentally we're creating a connection to a database which depends on 1. a database (name) to connect to and 2. a machine configuration (what we call profile).  If we change either of those we make a new connection.  Ok, I think I'm on board with any potential change to `connection`.
