### ISSUE TITLE
sdssdb latest cannot install sdsstools on python 3.6

### ISSUE THREAD

**Issue by havok2063** [sdss/sdssdb#27]
**Describe the bug**
The latest install of `sdssdb` fails on Python 3.6 now that `sdsstools` is a requirement.  I think this is because `sdsstools` has a python requirement >3.7 while `sdssdb` still has a python requirement >=3.6.  

**To Reproduce**
Within a Python 3.6 environment, run  `pip install -U --pre sdssdb`  or `pip install -e .` or `pip install .[all,dev]`
```
Collecting sdssdb
  Using cached https://files.pythonhosted.org/packages/29/56/584b067572cc9baa0d83e95d354796bd70c0205bfcd14e8a8db6bf3e27ab/sdssdb-0.3.3b2-py3-none-any.whl
Collecting numpy>=1.18.2 (from sdssdb)
  Downloading https://files.pythonhosted.org/packages/ec/b7/9a09a0322fce2999cc5168a71dd25ab64bd57103e607c3865132e4a5f304/numpy-1.18.2-cp36-cp36m-macosx_10_9_x86_64.whl (15.2MB)
     |████████████████████████████████| 15.2MB 17.7MB/s
Collecting sdsstools>=0.1.5 (from sdssdb)
  ERROR: Could not find a version that satisfies the requirement sdsstools>=0.1.5 (from sdssdb) (from versions: none)
ERROR: No matching distribution found for sdsstools>=0.1.5 (from sdssdb)
```
**Expected Behavior**
Either `sdsstools` should work on python 3.6 or if it that's not possible, then `sdssdb` minimum python version should bump to 3.7.

**Comment by albireox** [comment]
I'll have a look. I may be able to release an sdsstools that works with 3.6.

**Comment by havok2063** [comment]
Ok, sounds good.  I'm also fine bumping `sdssdb` to 3.7.  I don't use 3.6 myself, but also don't know how many other people are using 3.7+.   I only noticed it when tests for 3.6 started failing.

**Comment by albireox** [comment]
Can you do `pip install --upgrade --pre sdsstools` and see if that fixes it? I published a 0.1.7b1 version with the Python version relaxed to 3.6. Seems to work fine for me but haven't tested it extensively.

**Comment by havok2063** [comment]
That seems to have worked.  I did `pip install -U --pre sdssdb` which looks like it correctly installed the new `sdsstools.`

`Successfully installed docutils-0.16 numpy-1.18.2 sdssdb-0.3.3b2 sdsstools-0.1.7b1 semantic-version-2.8.4`  

Both `sdssdb` and `sdsstools` import correctly in a py3.6 environment.

**Comment by albireox** [comment]
Great. I'll release a full version of `sdsstools`.
