### ISSUE TITLE
Decide whether to install both peewee and SQLA or none

### ISSUE THREAD

**Issue by albireox** [sdss/sdssdb#32]
Currently we require both Peewee and SQLA in `install_requires` but also have a lot of `_peewee` and `_sqla` in the code to deal with cases in which only one of them is present. I think we need to decide whether:

- sdssdb does not require installing neither Peewee or SQLA. Keep the `_peewee` and `_sqla`. The advantage is that removes unnecessary packages from the install, but means having to pip install two things (sdssdb and the chosen ORM) and may be a bit confusing.

- Require both Peewee and SQLA as we do now but then simplify the code removing the `_peewee` and `_sqla`.

**Comment by havok2063** [comment]
I'm in favor of the second option.  I think `sdssdb` should be usable out-of-the-box after pip installing it.  There's only at most one unnecessary package, and that's if people only use one library over the other.  If we do decide on removing them, we might want to consider adding them to the `[dev]` and `[all]` sections.  I think for `[dev]` we would have to for testing.  I'm not sure if the `[docs]` needs them for building.

**Comment by albireox** [comment]
Sounds good. I also favour keeping the packages but wanted to check before removing the `_peewee` and `_sqla`. I think neither of them are problematic to install although I think SQLAlchemy does some compiling of C libraries.
