### ISSUE TITLE
Agree on database attribute name

### ISSUE THREAD

**Issue by albireox** [sdss/sdssdb#4]
I've been calling my `database` object `database` (e.g., `sdssdb.peewee.observatory.database`) while for SQLA it seems we have `db` (`sdssdb.sqlalchemy.sdss5db.db`). We should agree on one for consistency.

**Comment by havok2063** [comment]
oh yeah.  I'm fine one way or the other.  `database` is more clear and verbose but `db` is shorter to deal with.  I don't have a strong preference, but who knows what'll happen as I start using it.

**Comment by albireox** [comment]
I set this to `database` everywhere.
