### ISSUE TITLE
Decide on PY2 support

### ISSUE THREAD

**Issue by albireox** [sdss/sdssdb#5]
Are we supporting Python 2.7 or starting with 3.6?

**Comment by havok2063** [comment]
If we want to adopt this for current SDSS-IV software, then it should probably support Python 2.7.  But I'm also fine making it 3.6 only.

**Comment by albireox** [comment]
@jsobeck Just using `from __future__ import` doesn't ensure that the code will work in both Python 2 and 3.

I'd be in favour of having this product being 3-only, in part because it's just easier and in part because it may force people to start porting their codes to 3. Maybe we can start with that unless somebody raises a good point about keeping 2-compatibility.

**Comment by albireox** [comment]
Sounds good. Let's do that for now unless the hordes of users start taking the pitchforks out.
