### ISSUE TITLE
sdssdb import fails when peewee not installed

### ISSUE THREAD

**Issue by havok2063** [sdss/sdssdb#8]
If the `peewee` package is not installed, `sdssdb` fails to import, with the message 

```
In [1]: import sdssdb
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-c5c7d9c18ec0> in <module>
----> 1 import sdssdb

~/Work/github_projects/sdss/sdssdb/python/sdssdb/__init__.py in <module>
     55
     56
---> 57 from .connection import *  # noqa

AttributeError: module 'sdssdb.connection' has no attribute 'PeeweeDatabaseConnection'

```

Since `_peewee` is None, `PeeweeDatabaseConnection` is not created, but I think `__all__ = ['DatabaseConnection', 'PeeweeDatabaseConnection', 'SQLADatabaseConnection']
` makes the module try to import it anyways
 
Since `peewee` or `sqlalchemy` aren't in the list of `requirements`, I think it should at least import cleanly and maybe issue a warning if both `_peewee` and `_sqlalchemy` are None that `sdssdb` can't be used without at least one of them.

**Comment by albireox** [comment]
Have a look at #9.
